#include "image.h"
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <libheif/heif.h>
#include <string.h>

gboolean wpd_scale_mode_parse(const gchar*s,WpdScaleMode*o){if(!s||!g_strcmp0(s,"fill"))*o=WPD_SCALE_FILL;else if(!g_strcmp0(s,"fit"))*o=WPD_SCALE_FIT;else if(!g_strcmp0(s,"stretch"))*o=WPD_SCALE_STRETCH;else if(!g_strcmp0(s,"none"))*o=WPD_SCALE_NONE;else return FALSE;return TRUE;}
static gboolean is_heif(const gchar*p){const gchar*e=strrchr(p,'.');return e&&(!g_ascii_strcasecmp(e,".heif")||!g_ascii_strcasecmp(e,".heic"));}
static cairo_surface_t*from_pixbuf(GdkPixbuf*p){gint w=gdk_pixbuf_get_width(p),h=gdk_pixbuf_get_height(p),rs=gdk_pixbuf_get_rowstride(p),nc=gdk_pixbuf_get_n_channels(p);gboolean alpha=gdk_pixbuf_get_has_alpha(p);cairo_surface_t*s=cairo_image_surface_create(CAIRO_FORMAT_ARGB32,w,h);guchar*dst=cairo_image_surface_get_data(s),*src=gdk_pixbuf_get_pixels(p);gint stride=cairo_image_surface_get_stride(s);for(gint y=0;y<h;y++)for(gint x=0;x<w;x++){guchar*r=src+y*rs+x*nc;guint a=alpha?r[3]:255;guint32 v=(a<<24)|((r[0]*a/255)<<16)|((r[1]*a/255)<<8)|(r[2]*a/255);memcpy(dst+y*stride+x*4,&v,4);}cairo_surface_mark_dirty(s);return s;}
static cairo_surface_t*load_heif(const gchar*p,GError**err){struct heif_context*c=heif_context_alloc();struct heif_error e=heif_context_read_from_file(c,p,NULL);if(e.code!=heif_error_Ok){g_set_error(err,G_FILE_ERROR,G_FILE_ERROR_FAILED,"HEIF: %s",e.message);heif_context_free(c);return NULL;}struct heif_image_handle*h=NULL;e=heif_context_get_primary_image_handle(c,&h);if(e.code!=heif_error_Ok){g_set_error(err,G_FILE_ERROR,G_FILE_ERROR_FAILED,"HEIF: %s",e.message);heif_context_free(c);return NULL;}struct heif_image*i=NULL;e=heif_decode_image(h,&i,heif_colorspace_RGB,heif_chroma_interleaved_RGBA,NULL);if(e.code!=heif_error_Ok){g_set_error(err,G_FILE_ERROR,G_FILE_ERROR_FAILED,"HEIF: %s",e.message);heif_image_handle_release(h);heif_context_free(c);return NULL;}int stride,w=heif_image_handle_get_width(h),hh=heif_image_handle_get_height(h);const uint8_t*d=heif_image_get_plane_readonly(i,heif_channel_interleaved,&stride);GdkPixbuf*pb=gdk_pixbuf_new_from_data(d,GDK_COLORSPACE_RGB,TRUE,8,w,hh,stride,NULL,NULL);cairo_surface_t*s=from_pixbuf(pb);g_object_unref(pb);heif_image_release(i);heif_image_handle_release(h);heif_context_free(c);return s;}
cairo_surface_t*wpd_image_load(const gchar*p,GError**e){if(is_heif(p))return load_heif(p,e);GdkPixbuf*pb=gdk_pixbuf_new_from_file(p,e);if(!pb)return NULL;cairo_surface_t*s=from_pixbuf(pb);g_object_unref(pb);return s;}
cairo_surface_t*wpd_image_render(const gchar*p,gint w,gint h,WpdScaleMode m,GError**e){cairo_surface_t*src=wpd_image_load(p,e);if(!src)return NULL;gint sw=cairo_image_surface_get_width(src),sh=cairo_image_surface_get_height(src);cairo_surface_t*out=cairo_image_surface_create(CAIRO_FORMAT_ARGB32,w,h);cairo_t*cr=cairo_create(out);cairo_set_source_rgb(cr,0,0,0);cairo_paint(cr);double sx=1,sy=1,x=0,y=0;if(m==WPD_SCALE_STRETCH){sx=(double)w/sw;sy=(double)h/sh;}else if(m!=WPD_SCALE_NONE){double z=m==WPD_SCALE_FILL?MAX((double)w/sw,(double)h/sh):MIN((double)w/sw,(double)h/sh);sx=sy=z;}x=(w-sw*sx)/2;y=(h-sh*sy)/2;cairo_translate(cr,x,y);cairo_scale(cr,sx,sy);cairo_set_source_surface(cr,src,0,0);cairo_pattern_set_filter(cairo_get_source(cr),CAIRO_FILTER_BILINEAR);cairo_paint(cr);cairo_destroy(cr);cairo_surface_destroy(src);return out;}
